name: syncfusion_flutter_pdf
description: The Flutter PDF is a library written natively in Dart for creating, reading, editing, and securing PDF files in Android, iOS, and web platforms.
version: 29.1.33
homepage: https://github.com/syncfusion/flutter-widgets/tree/master/packages/syncfusion_flutter_pdf

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  intl: '>=0.18.0 <0.21.0'
  xml: ">=6.5.0 <7.0.0"
  crypto: ">=3.0.0 <4.0.0"
  convert: ">=3.0.0 <4.0.0"
  pure_dart_ui: ">=0.1.0 <0.2.0"
  http: ">=1.2.1 <2.0.0"


